all:
	g++ -c point.h dijkstra.h read_file.h all_paths.h path.h
	g++ test_all_paths.cpp 

headers: 
	g++ -c point.h dijkstra.h read_file.h all_paths.h path.h

code: 
#	g++ steiner_4.cpp

run: 
	./a.out
	

clean: 
	rm *.gch a.out
	clear 
